aplications/portafolio/urls.py
from django.urls import path
from . import views

app_name = "portafolio_app"

urlpatterns = [
    path(
        '',
        views.HomeView.as_view(),
        name="home"
    ),
    path(
        'proyectos',
        views.ListProyectos.as_view(),
        name="proyectos"),
    path(
        'contacto',
        views.EnviarCorreo.as_view(),
        name="contactos"),
    path(
        'emailTemplate',
        views.EmailTemplate.as_view(),
        name="emailTemplate"),        
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("aplications.portafolio.urls"))
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

aplications/portafolio/models.py
from django.db import models

# Create your models here.

class Proyectos(models.Model):

    titulo = models.CharField("Titulo:", max_length=50)
    descripcion = models.CharField("Descripcion:", max_length=250)
    imagen = models.ImageField("Imagen:", upload_to="imagen-proyectos", height_field=None, width_field=None, max_length=None)
    url = models.URLField("URL:", max_length=200)

    class Meta:
        
        verbose_name = "Proyecto"
        verbose_name_plural = "Proyectos"

    def __str__(self):
        return self.titulo + "-" + self.url

class Correos(models.Model):

    nombre = models.CharField("Nombre Completo:", max_length=100)
    email = models.EmailField("Email:", max_length=250)
    mensaje = models.TextField("Mensaje:", max_length=250,)
    leido = models.BooleanField(default=False,blank=True)
    

    class Meta:
        
        verbose_name = "Correo"
        verbose_name_plural = "Correos"

    def __str__(self):
        return self.nombre + "-" + self.email




            
        
        

aplications/portafolio/forms.py
from django import forms
from .models import Correos

class CorreoForm(forms.ModelForm):

    class Meta:
        model = Correos
        fields = (
            'nombre',
            'email',
            'mensaje',
        )

        widgets = {
            "nombre":forms.TextInput(
                attrs= {
                    "placeholder":"Nombre Completo",
                    
                },
            ),
            "email":forms.TextInput(
                attrs={
                    "placeholder":"Ingrese su correo",
                    
                }
            ),
            "mensaje":forms.TextInput(
                attrs={
                    "placeholder":"Deje su mensaje",
                      
                    
                }
            )
        } 
          


        

aplications/portafolio/views.py
from email.message import EmailMessage
from django.shortcuts import render
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import FormView
from django.core.mail import send_mail
from django.urls import reverse_lazy
from .models import Proyectos,Correos
from .forms import CorreoForm
# Create your views here.

class HomeView(TemplateView):
    template_name = "portafolio/home.html"


class ListProyectos(ListView):
    template_name = "portafolio/list-proyectos.html"
    model = Proyectos
    context_object_name = "projects"

class EmailTemplate(TemplateView):
    template_name = "portafolio/send-email.html"

class EnviarCorreo(FormView):
    template_name= "portafolio/contacto.html"
    form_class = CorreoForm
    success_url = reverse_lazy("portafolio_app:emailTemplate")

    def form_valid(self, form):
        Correos.objects.create(
            nombre = form.cleaned_data["nombre"],
            email = form.cleaned_data["email"],
            mensaje = form.cleaned_data["mensaje"],        
        )

        
        asunto = "mensaje de cliente nuevo: " + form.cleaned_data["nombre"]
        mensaje = form.cleaned_data["mensaje"] + "cuenta de contacto:  " + form.cleaned_data["email"]
        
        send_mail(asunto,mensaje,"victor26lanza@gmail.com",['victorlnz2600@gmail.com'])  

        return super(EnviarCorreo,self).form_valid(form)

    


  



        



    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik&family=Rufina:wght@400;700&display=swap" rel="stylesheet">
    <title>{% block titulo %} {% endblock titulo %}</title>
</head>
<body>
{% block content %}
    
{% endblock content %}        
</body>
</html>

templates/includes/footer.html
{% load static %}
<div class="footer">
    <div class="center full-width">
        <div class="row">
            <h3>Contactame</h3>
        </div>
    </div>
    <div class="center full-width">
        <div class="row">
            <p>Tambien puedes seguirme en mis redes sociales</p>
        </div>
    </div>
    <div class="center full-width social-links">
        <div class="row">
            <a href="https://www.linkedin.com/in/victor-lanza-844320244" target="_blank"><img src="{% static 'img/linkedin.png' %}" alt="" class="social" width="30"></a>
            <a href="https://twitter.com/VictorDLaw26?s=08" target="_blank"><img src="{% static 'img/twitter.png' %}" alt="" class="social" width="30"></a>
        </div>
    </div>

</div>

templates/includes/header.html
<header class="header">
    <div class="logo">Victor Lanza</div>
    <nav>
        <ul>
            <li><a href="{% url 'portafolio_app:home' %}" style="text-decoration: none ;">Inicio</a></li>
            <li><a href="{% url 'portafolio_app:proyectos' %}">Proyectos</a></li>
            <li><a href="{% url 'portafolio_app:contactos' %}">Contacto</a></li>
        </ul>
    </nav>
</header>

templates/includes/seccion1.html
<div class="center">
    <div class="content">
        <div class="row vert-pad">
            <div class="left padded">
                <h1 class="titulos">Desarrollo aplicaciones y paginas web funcionales y de alto nivel</h1>
                <p class="parrafos">Constantemente me encuentro aprendiendo nuevas tecnologias</p>
                <p class="parrafos">Web creada desde 0 con mis conocimientos en Django,Mysql,CSS </p>                
            </div>
            <div class="right padded">
                <h1 class="titulos">si no estas convencido puedes checar mi CV</h1>
                <a href="" class="btn">pincha aqui</a>
            </div>
        </div>

    </div>

</div>

   

templates/portafolio/contacto.html
{% extends 'base.html' %}


{% block titulo %} Contactos {% endblock titulo %}


{% block content %}

{% include 'includes/header.html' %}

<div class="center padded">
    <div class="content">
        <div class="row vert-pad">
            <div class="left padded">
                <h1>Puedes dejarme un correo! :)</h1>
                <p class="parrafos">Que estas esperando? contrata a un desarrollador de primer nivel</p>
            </div>
            <div class="right padded">
                <form method="post" class="contact-form">{% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn full-width">Enviar</button>
                </form>
            </div>

        </div>

    </div>

</div>
{% include 'includes/footer.html' %}
{% endblock content %}
    
    

templates/portafolio/home.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %} Victor Lanza {% endblock titulo %}


{% block content %}
    {% include 'includes/header.html' %}
    <div class="hero">
        <div class="hero-content">
            <div class="left">
                <h1 class="titulos">Victor Lanza</h1>
                <h3 class="titulos">Backend developer</h3>
                <p>Construyo aplicaciones dinamicas utilizando frameworks como django y flask</p>
                <a href="{% url 'portafolio_app:contactos' %}" class="btn">Contacto</a>
            </div>
            <div class="right">
                <img src="{% static 'img/desarollador.png' %}" alt="developer" width="600px">
            </div>
        </div>            
    </div>
    {% include 'includes/seccion1.html' %}

    {% include 'includes/footer.html' %}
        
{% endblock content %}
    
    

templates/portafolio/list-proyectos.html
{% extends 'base.html' %}

{% block titulo %} Proyectos {% endblock titulo %}


{% block content %}
{% include 'includes/header.html' %}

<div class="center padded">
    <div class="content padded">
        <div class="padded">
            <h1>Proyectos Construidos</h1>
        </div>
        
        {% for p in projects %}                    
        <div class="row-project">
            <div class="card third">
                <h3>{{ p.titulo }}</h3>
                <p>{{ p.descripcion }}</p>
                <hr>
                <img src="{{ p.imagen.url }}" alt="" width="200px" height="200px" class="img-p">
                <br>
                <a href="{{ p.url }}" target="_blank" style="text-decoration:none; background-color: #ABD9FF; color: black; border-radius: 5px; font-size: 15px; padding: 5px 10px; font-weight: 700;">link aqui</a>
            </div>
        </div>
        {% endfor %}        
    </div>    
</div>
{% include 'includes/footer.html' %}        

{% endblock content %}
    

templates/portafolio/send-email.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %} Mensaje enviado {% endblock titulo %}

{% block content %}
{% include 'includes/header.html' %}
 <div class="hero">
    <div class="hero-content">
        <div class="left">
            <h1>Excelente! Mensaje enviado!</h1>
            <p>Pronto tendras respuesta de victor</p>
        </div>
        <div class="right">
            <img src="{% static 'img/email.png' %}" alt="" width="600px">
        </div>
    </div>
 </div>
{% include 'includes/footer.html' %}     
{% endblock content %}
    
    